#!/bin/sh
set -euo pipefail

export DENO_DIR=/tmp/.deno-dir
export LOCAL_TMP_DIR=/tmp/exec-env
${LAMBDA_RUNTIME_DIR}/deno run \
  --allow-env \
  --allow-net \
  --allow-read=$LOCAL_TMP_DIR \
  --allow-write=$LOCAL_TMP_DIR \
  ${LAMBDA_RUNTIME_DIR}/aws-runtime.ts
